package com.ilham.made.thirdsubmission.model

data class MatchFavoriteModel(
    var id: Int? = null,
    val idEvent: Int = 0,
    val strSport: String? = null,
    val idLeague: Int? = null,
    val strLeague: String? = null,
    val strSeason: String? = null,
    val strHomeTeam: String? = null,
    val strAwayTeam: String? = null,
    val intHomeScore: Int? = null,
    val intAwayScore: Int? = null,
    val intRound: Int? = null,
    val strHomeGoalDetails: String? = null,
    val strHomeRedCards: String? = null,
    val strHomeYellowCards: String? = null,
    val strHomeLineupGoalkeeper: String? = null,
    val strHomeLineupDefense: String? = null,
    val strHomeLineupMidfield: String? = null,
    val strHomeLineupForward: String? = null,
    val strHomeFormation: String? = null,
    val strAwayGoalDetails: String? = null,
    val strAwayRedCards: String? = null,
    val strAwayYellowCards: String? = null,
    val strAwayLineupGoalkeeper: String? = null,
    val strAwayLineupDefense: String? = null,
    val strAwayLineupMidfield: String? = null,
    val strAwayLineupForward: String? = null,
    val strAwayFormation: String? = null,
    val intHomeShots: Int? = null,
    val intAwayShots: Int? = null,
    val dateEvent: String? = null,
    val strTime: String? = null,
    val strDate: String? = null,
    val idHomeTeam: Int? = null,
    val idAwayTeam: Int? = null,
    val strPostponed: String? = null,
    var strBadgeHomeTeam: String? = null,
    var strBadgeAwayTeam: String? = null
)
